
import * as cartAction from '../crunch_cart/actionTypes'

export let initialTempCart =(window.cartInfo)?window.cartInfo:{
	"414": {
	  "2906": [
		{
		  "sno": "80992",
		  "siteKey": "6ecb051146999ad8f9e3b2ed52f0426b",
		  "mallSno": "1",
		  "directCart": "n",
		  "memNo": "0",
		  "goodsNo": "1002565326",
		  "optionSno": "11242610",
		  "goodsCnt": "8",
		  "deliveryCollectFl": "pre",
		  "deliveryMethodFl": "delivery",
		  "memberCouponNo": "",
		  "tmpOrderNo": "",
		  "useBundleGoods": "1",
		  "linkMainTheme": "",
		  "regDt": "2019-01-17 14:03:51",
		  "goodsNm": "BnS 마티즈2 코일 카매트 풀세트/냄새 No",
		  "goodsDisplayFl": "y",
		  "goodsDisplayMobileFl": "y",
		  "goodsSellFl": "y",
		  "goodsSellMobileFl": "y",
		  "scmNo": "414",
		  "commission": "12.00",
		  "goodsCd": "",
		  "cateCd": "004025013003",
		  "goodsOpenDt": "0000-00-00 00:00:00",
		  "goodsState": "n",
		  "brandCd": "",
		  "makerNm": "",
		  "originNm": "",
		  "hscode": "",
		  "goodsModelNo": "",
		  "goodsPermission": "all",
		  "goodsPermissionGroup": "",
		  "goodsPermissionPriceStringFl": "n",
		  "goodsPermissionPriceString": "",
		  "onlyAdultFl": "n",
		  "onlyAdultImageFl": "n",
		  "taxFreeFl": "t",
		  "taxPercent": "10.0",
		  "goodsWeight": "0.00",
		  "totalStock": "0",
		  "stockFl": "n",
		  "soldOutFl": "n",
		  "fixedSales": "option",
		  "fixedOrderCnt": "option",
		  "salesUnit": "1",
		  "minOrderCnt": "1",
		  "maxOrderCnt": "0",
		  "salesStartYmd": "0000-00-00 00:00:00",
		  "salesEndYmd": "0000-00-00 00:00:00",
		  "mileageFl": "c",
		  "mileageGroup": "all",
		  "mileageGoods": "0.00",
		  "mileageGoodsUnit": "percent",
		  "mileageGroupInfo": "",
		  "mileageGroupMemberInfo": "{}",
		  "fixedGoodsDiscount": "",
		  "goodsDiscountGroup": "all",
		  "goodsDiscountGroupMemberInfo": "{}",
		  "exceptBenefit": "",
		  "exceptBenefitGroup": "",
		  "exceptBenefitGroupInfo": "",
		  "payLimitFl": "n",
		  "payLimit": "",
		  "goodsPriceString": "",
		  "optionFl": "n",
		  "optionTextFl": "y",
		  "addGoodsFl": "n",
		  "addGoods": [],
		  "deliverySno": "2906",
		  "goodsUnitPrice1": "68900.00",
		  "goodsUnitPrice2": "68800.00",
		  "goodsUnitPrice3": "68700.00",
		  "goodsUnitPrice4": "68600.00",
		  "goodsUnitPrice5": "68500.00",
		  "goodsUnitPrice6": "68400.00",
		  "goodsUnitPrice7": "68300.00",
		  "goodsUnitPrice8": "68200.00",
		  "goodsUnitPrice9": "68100.00",
		  "goodsUnitPrice10": "68000.00",
		  "optionCostPrice": "0.00",
		  "optionCode": "",
		  "optionViewFl": "y",
		  "optionSellFl": "y",
		  "stockCnt": "0",
		  "optionValue1": "",
		  "optionValue2": "",
		  "optionValue3": "",
		  "optionValue4": "",
		  "optionValue5": "",
		  "optionMemo": "",
		  "optionGoodsUnitprice1": "",
		  "optionGoodsUnitprice2": "",
		  "optionGoodsUnitprice3": "",
		  "optionGoodsUnitprice4": "",
		  "optionGoodsUnitprice5": "",
		  "optionGoodsUnitprice6": "",
		  "optionGoodsUnitprice7": "",
		  "optionGoodsUnitprice8": "",
		  "optionGoodsUnitprice9": "",
		  "optionGoodsUnitprice10": "",
		  "imageSize": "0",
		  "goodsNmStandard": "BnS 마티즈2 코일 카매트 풀세트/냄새 No",
		  "cateAllCd": [
			{
			  "sno": "12611131",
			  "cateCd": "004",
			  "cateLinkFl": "y",
			  "goodsSort": 0,
			  "fixSort": 0
			},
			{
			  "sno": "12611132",
			  "cateCd": "004025",
			  "cateLinkFl": "y",
			  "goodsSort": 0,
			  "fixSort": 0
			},
			{
			  "sno": "12611133",
			  "cateCd": "004025013",
			  "cateLinkFl": "y",
			  "goodsSort": 0,
			  "fixSort": 0
			},
			{
			  "sno": "12611134",
			  "cateCd": "004025013003",
			  "cateLinkFl": "y",
			  "goodsSort": 0,
			  "fixSort": 0
			}
		  ],
		  "optionTextInfo": {
			"85847": {
			  "optionSno": "85847",
			  "optionName": "차종/연식입력",
			  "baseOptionTextPrice": "0.00"
			}
		  },
		  "addGoodsMustFl": null,
		  "orderPossible": "y",
		  "stockOver": "n",
		  "orderPossibleMessageList": [],
		  "goodsPriceDisplayFl": "y",
		  "duplicationGoods": "n",
		  "goodsType": "goods",
		  "goodsImage": "<img src=\"https://shop-phinf.pstatic.net/20151123_54/nmp_1448269777909ogqBv_JPEG/188671.jpg?type=m450\" width=\"40\" alt=\"BnS 마티즈2 코일 카매트 풀세트/냄새 No\" title=\"BnS 마티즈2 코일 카매트 풀세트/냄새 No\" class=\"middle\" class=\"imgsize-s\" />",
		  "goodsMileageExcept": "n",
		  "couponBenefitExcept": "n",
		  "memberBenefitExcept": "n",
		  "timeSaleFl": false,
		  "goodsDeliveryMethodFl": "delivery",
		  "goodsDeliveryMethodFlText": "택배",
		  "optionNm": "",
		  "goodsKey": 2,
		  "goodsMileageAddInfo": {
			"mileageFl": "c",
			"mileageGroup": "all",
			"mileageGoods": "0.00",
			"mileageGoodsUnit": "percent"
		  },
		  "price": {
			"fixedPrice": "0.00",
			"costPrice": "0.00",
			"baseGoodsPrice": "68200.00",
			"baseOptionPrice": "0.00",
			"baseOptionTextPrice": 0,
			"goodsPrice": "68200.00",
			"optionPrice": "0.00",
			"optionCostPrice": "0.00",
			"optionTextPrice": 0,
			"goodsPriceSum": 545600,
			"optionPriceSum": 0,
			"optionTextPriceSum": 0,
			"addGoodsPriceSum": 0,
			"addGoodsVat": {
			  "supply": 0,
			  "tax": 0
			},
			"goodsDcPrice": 0,
			"memberDcPrice": 0,
			"memberOverlapDcPrice": 0,
			"couponGoodsDcPrice": null,
			"goodsDeliveryPrice": 0,
			"timeSalePrice": null,
			"goodsCnt": "8",
			"goodsMemberBankDcPrice": 0,
			"goodsMemberDcPrice": 0,
			"goodsMemberOverlapDcPrice": 0,
			"goodsCouponGoodsDcPrice": 0,
			"addGoodsMemberDcPrice": 0,
			"addGoodsMemberOverlapDcPrice": 0,
			"addGoodsCouponGoodsDcPrice": 0,
			"goodsPriceSubtotal": 545600,
			"goodsVat": {
			  "supply": 496000,
			  "tax": "49600"
			},
			"goodsDeliveryAreaPrice": 0,
			"goodsDeliveryCollectPrice": 0,
			"goodsDeliveryWholeFreePrice": 0
		  },
		  "option": [],
		  "optionText": [
			{
			  "optionSno": "85847",
			  "optionName": "차종/연식입력",
			  "baseOptionTextPrice": "0.00",
			  "optionTextPrice": "0.00",
			  "optionValue": "ssss"
			}
		  ],
		  "mileage": {
			"goodsMileage": 5456,
			"memberMileage": null,
			"couponGoodsMileage": null,
			"goodsGoodsMileage": 0,
			"goodsMemberMileage": 0,
			"goodsCouponGoodsMileage": 0,
			"addGoodsGoodsMileage": 0,
			"addGoodsMemberMileage": 0,
			"addGoodsCouponGoodsMileage": 0
		  },
		  "coupon": [],
		  "memberDcInfo": "{\"addDcFl\":null,\"overlapDcFl\":null,\"memberDcPrice\":0,\"memberBankDcPrice\":0,\"memberOverlapDcPrice\":0,\"dcPercent\":null,\"overlapDcPercent\":null,\"goodsCnt\":\"8\"}",
		  "addDcFl": null,
		  "overlapDcFl": null,
		  "priceInfo": "{\"fixedPrice\":\"0.00\",\"costPrice\":\"0.00\",\"baseGoodsPrice\":\"68200.00\",\"baseOptionPrice\":\"0.00\",\"baseOptionTextPrice\":0,\"goodsPrice\":\"68200.00\",\"optionPrice\":\"0.00\",\"optionCostPrice\":\"0.00\",\"optionTextPrice\":0,\"goodsPriceSum\":545600,\"optionPriceSum\":0,\"optionTextPriceSum\":0,\"addGoodsPriceSum\":0,\"addGoodsVat\":{\"supply\":0,\"tax\":0},\"goodsDcPrice\":0,\"memberDcPrice\":0,\"memberOverlapDcPrice\":0,\"couponGoodsDcPrice\":null,\"goodsDeliveryPrice\":0,\"timeSalePrice\":null,\"goodsCnt\":\"8\",\"goodsMemberBankDcPrice\":0,\"goodsMemberDcPrice\":0,\"goodsMemberOverlapDcPrice\":0,\"goodsCouponGoodsDcPrice\":0,\"addGoodsMemberDcPrice\":0,\"addGoodsMemberOverlapDcPrice\":0,\"addGoodsCouponGoodsDcPrice\":0,\"goodsPriceSubtotal\":545600,\"goodsVat\":{\"supply\":496000,\"tax\":\"49600\"}}",
		  "mileageInfo": "{\"goodsMileage\":5456,\"memberMileage\":null,\"couponGoodsMileage\":null,\"goodsGoodsMileage\":0,\"goodsMemberMileage\":0,\"goodsCouponGoodsMileage\":0,\"addGoodsGoodsMileage\":0,\"addGoodsMemberMileage\":0,\"addGoodsCouponGoodsMileage\":0,\"goodsCnt\":\"8\"}",
		  "goodsDcPricePrint": 545600,
		  "memberDcTotalPercent": "0%",
		  "memberDcPricePrint": 545600,
		  "periodDiscountEndPrint": "",
		  "goodsDeliveryFl": "y",
		  "goodsDeliveryFixFl": "free",
		  "goodsDeliveryMethod": "기본 - 배송비무료",
		  "goodsDeliveryCollectFl": "pre",
		  "goodsDeliveryWholeFreeFl": true,
		  "goodsDeliveryTaxFreeFl": "t",
		  "goodsDeliveryTaxPercent": "10.0"
		}
	  ]
	},
	"672": {
	  "4800": [
		{
		  "sno": "80854",
		  "siteKey": "6ecb051146999ad8f9e3b2ed52f0426b",
		  "mallSno": "1",
		  "directCart": "n",
		  "memNo": "0",
		  "goodsNo": "1002548526",
		  "optionSno": "11200569",
		  "goodsCnt": "1",
		  "deliveryCollectFl": "pre",
		  "deliveryMethodFl": "delivery",
		  "memberCouponNo": "",
		  "tmpOrderNo": "",
		  "useBundleGoods": "1",
		  "linkMainTheme": "",
		  "regDt": "2019-01-17 13:31:36",
		  "goodsNm": "마블 황사마스크 1매용",
		  "goodsDisplayFl": "y",
		  "goodsDisplayMobileFl": "y",
		  "goodsSellFl": "y",
		  "goodsSellMobileFl": "y",
		  "scmNo": "672",
		  "commission": "12.00",
		  "goodsCd": "",
		  "cateCd": "004001006",
		  "goodsOpenDt": "0000-00-00 00:00:00",
		  "goodsState": "n",
		  "brandCd": "",
		  "makerNm": "",
		  "originNm": "",
		  "hscode": "",
		  "goodsModelNo": "",
		  "goodsPermission": "all",
		  "goodsPermissionGroup": "",
		  "goodsPermissionPriceStringFl": "n",
		  "goodsPermissionPriceString": "n",
		  "onlyAdultFl": "n",
		  "onlyAdultImageFl": "n",
		  "taxFreeFl": "t",
		  "taxPercent": "10.0",
		  "goodsWeight": "0.00",
		  "totalStock": "100000",
		  "stockFl": "y",
		  "soldOutFl": "n",
		  "fixedSales": "option",
		  "fixedOrderCnt": "option",
		  "salesUnit": "1",
		  "minOrderCnt": "1",
		  "maxOrderCnt": "0",
		  "salesStartYmd": "0000-00-00 00:00:00",
		  "salesEndYmd": "0000-00-00 00:00:00",
		  "mileageFl": "c",
		  "mileageGroup": "all",
		  "mileageGoods": "0.00",
		  "mileageGoodsUnit": "percent",
		  "mileageGroupInfo": "",
		  "mileageGroupMemberInfo": "null",
		  "fixedGoodsDiscount": "",
		  "goodsDiscountGroup": "all",
		  "goodsDiscountGroupMemberInfo": "null",
		  "exceptBenefit": "",
		  "exceptBenefitGroup": "",
		  "exceptBenefitGroupInfo": "",
		  "payLimitFl": "n",
		  "payLimit": "",
		  "goodsPriceString": "",
		  "optionFl": "n",
		  "optionTextFl": "n",
		  "addGoodsFl": "n",
		  "addGoods": [],
		  "deliverySno": "4800",
		  "goodsUnitPrice1": "1200.00",
		  "goodsUnitPrice2": "1200.00",
		  "goodsUnitPrice3": "0.00",
		  "goodsUnitPrice4": "0.00",
		  "goodsUnitPrice5": "0.00",
		  "goodsUnitPrice6": "0.00",
		  "goodsUnitPrice7": "0.00",
		  "goodsUnitPrice8": "0.00",
		  "goodsUnitPrice9": "0.00",
		  "goodsUnitPrice10": "0.00",
		  "optionCostPrice": "0.00",
		  "optionCode": "",
		  "optionViewFl": "y",
		  "optionSellFl": "y",
		  "stockCnt": "100000",
		  "optionValue1": "",
		  "optionValue2": "",
		  "optionValue3": "",
		  "optionValue4": "",
		  "optionValue5": "",
		  "optionMemo": "",
		  "optionGoodsUnitprice1": "",
		  "optionGoodsUnitprice2": "",
		  "optionGoodsUnitprice3": "",
		  "optionGoodsUnitprice4": "",
		  "optionGoodsUnitprice5": "",
		  "optionGoodsUnitprice6": "",
		  "optionGoodsUnitprice7": "",
		  "optionGoodsUnitprice8": "",
		  "optionGoodsUnitprice9": "",
		  "optionGoodsUnitprice10": "",
		  "imageSize": "150",
		  "goodsNmStandard": "마블 황사마스크 1매용",
		  "cateAllCd": [
			{
			  "sno": "12547562",
			  "cateCd": "004",
			  "cateLinkFl": "y",
			  "goodsSort": 0,
			  "fixSort": 0
			},
			{
			  "sno": "12547563",
			  "cateCd": "004001",
			  "cateLinkFl": "y",
			  "goodsSort": 0,
			  "fixSort": 0
			},
			{
			  "sno": "12547564",
			  "cateCd": "004001006",
			  "cateLinkFl": "y",
			  "goodsSort": 0,
			  "fixSort": 0
			}
		  ],
		  "addGoodsMustFl": null,
		  "orderPossible": "y",
		  "stockOver": "n",
		  "orderPossibleMessageList": [],
		  "goodsPriceDisplayFl": "y",
		  "duplicationGoods": "n",
		  "goodsType": "goods",
		  "goodsImage": "<img src=\"http://ai.esmplus.com/printplan/mask1-1.jpg\" width=\"40\" alt=\"마블 황사마스크 1매용\" title=\"마블 황사마스크 1매용\" class=\"middle\" class=\"imgsize-s\" />",
		  "goodsMileageExcept": "n",
		  "couponBenefitExcept": "n",
		  "memberBenefitExcept": "n",
		  "timeSaleFl": false,
		  "goodsDeliveryMethodFl": "delivery",
		  "goodsDeliveryMethodFlText": "택배",
		  "optionNm": "",
		  "goodsKey": 3,
		  "goodsMileageAddInfo": {
			"mileageFl": "c",
			"mileageGroup": "all",
			"mileageGoods": "0.00",
			"mileageGoodsUnit": "percent"
		  },
		  "price": {
			"fixedPrice": "0.00",
			"costPrice": "0.00",
			"baseGoodsPrice": "1200.00",
			"baseOptionPrice": "0.00",
			"baseOptionTextPrice": 0,
			"goodsPrice": "1200.00",
			"optionPrice": "0.00",
			"optionCostPrice": "0.00",
			"optionTextPrice": 0,
			"goodsPriceSum": 1200,
			"optionPriceSum": 0,
			"optionTextPriceSum": 0,
			"addGoodsPriceSum": 0,
			"addGoodsVat": {
			  "supply": 0,
			  "tax": 0
			},
			"goodsDcPrice": 0,
			"memberDcPrice": 0,
			"memberOverlapDcPrice": 0,
			"couponGoodsDcPrice": null,
			"goodsDeliveryPrice": 0,
			"timeSalePrice": null,
			"goodsCnt": "1",
			"goodsMemberBankDcPrice": 0,
			"goodsMemberDcPrice": 0,
			"goodsMemberOverlapDcPrice": 0,
			"goodsCouponGoodsDcPrice": 0,
			"addGoodsMemberDcPrice": 0,
			"addGoodsMemberOverlapDcPrice": 0,
			"addGoodsCouponGoodsDcPrice": 0,
			"goodsPriceSubtotal": 1200,
			"goodsVat": {
			  "supply": 1091,
			  "tax": "109"
			},
			"goodsDeliveryAreaPrice": 0,
			"goodsDeliveryCollectPrice": 0,
			"goodsDeliveryWholeFreePrice": 0
		  },
		  "option": [],
		  "optionText": [],
		  "mileage": {
			"goodsMileage": 12,
			"memberMileage": null,
			"couponGoodsMileage": null,
			"goodsGoodsMileage": 0,
			"goodsMemberMileage": 0,
			"goodsCouponGoodsMileage": 0,
			"addGoodsGoodsMileage": 0,
			"addGoodsMemberMileage": 0,
			"addGoodsCouponGoodsMileage": 0
		  },
		  "coupon": [],
		  "memberDcInfo": "{\"addDcFl\":null,\"overlapDcFl\":null,\"memberDcPrice\":0,\"memberBankDcPrice\":0,\"memberOverlapDcPrice\":0,\"dcPercent\":null,\"overlapDcPercent\":null,\"goodsCnt\":\"1\"}",
		  "addDcFl": null,
		  "overlapDcFl": null,
		  "priceInfo": "{\"fixedPrice\":\"0.00\",\"costPrice\":\"0.00\",\"baseGoodsPrice\":\"1200.00\",\"baseOptionPrice\":\"0.00\",\"baseOptionTextPrice\":0,\"goodsPrice\":\"1200.00\",\"optionPrice\":\"0.00\",\"optionCostPrice\":\"0.00\",\"optionTextPrice\":0,\"goodsPriceSum\":1200,\"optionPriceSum\":0,\"optionTextPriceSum\":0,\"addGoodsPriceSum\":0,\"addGoodsVat\":{\"supply\":0,\"tax\":0},\"goodsDcPrice\":0,\"memberDcPrice\":0,\"memberOverlapDcPrice\":0,\"couponGoodsDcPrice\":null,\"goodsDeliveryPrice\":0,\"timeSalePrice\":null,\"goodsCnt\":\"1\",\"goodsMemberBankDcPrice\":0,\"goodsMemberDcPrice\":0,\"goodsMemberOverlapDcPrice\":0,\"goodsCouponGoodsDcPrice\":0,\"addGoodsMemberDcPrice\":0,\"addGoodsMemberOverlapDcPrice\":0,\"addGoodsCouponGoodsDcPrice\":0,\"goodsPriceSubtotal\":1200,\"goodsVat\":{\"supply\":1091,\"tax\":\"109\"}}",
		  "mileageInfo": "{\"goodsMileage\":12,\"memberMileage\":null,\"couponGoodsMileage\":null,\"goodsGoodsMileage\":0,\"goodsMemberMileage\":0,\"goodsCouponGoodsMileage\":0,\"addGoodsGoodsMileage\":0,\"addGoodsMemberMileage\":0,\"addGoodsCouponGoodsMileage\":0,\"goodsCnt\":\"1\"}",
		  "goodsDcPricePrint": 1200,
		  "memberDcTotalPercent": "0%",
		  "memberDcPricePrint": 1200,
		  "periodDiscountEndPrint": "",
		  "goodsDeliveryFl": "y",
		  "goodsDeliveryFixFl": "fixed",
		  "goodsDeliveryMethod": "기본 - 고정배송비",
		  "goodsDeliveryCollectFl": "pre",
		  "goodsDeliveryWholeFreeFl": "n",
		  "goodsDeliveryTaxFreeFl": "t",
		  "goodsDeliveryTaxPercent": "10.0"
		}
	  ]
	},
	"737": {
	  "6047": [
		{
		  "sno": "80784",
		  "siteKey": "6ecb051146999ad8f9e3b2ed52f0426b",
		  "mallSno": "1",
		  "directCart": "n",
		  "memNo": "0",
		  "goodsNo": "1002302554",
		  "optionSno": "10603785",
		  "goodsCnt": "1",
		  "deliveryCollectFl": "pre",
		  "deliveryMethodFl": "delivery",
		  "memberCouponNo": "",
		  "tmpOrderNo": "",
		  "useBundleGoods": "1",
		  "linkMainTheme": "",
		  "regDt": "2019-01-17 12:23:00",
		  "goodsNm": "건조대 실내 건조대1단",
		  "goodsDisplayFl": "y",
		  "goodsDisplayMobileFl": "y",
		  "goodsSellFl": "y",
		  "goodsSellMobileFl": "y",
		  "scmNo": "737",
		  "commission": "12.00",
		  "goodsCd": "",
		  "cateCd": "004015003001",
		  "goodsOpenDt": "0000-00-00 00:00:00",
		  "goodsState": "n",
		  "brandCd": "",
		  "makerNm": "",
		  "originNm": "",
		  "hscode": "",
		  "goodsModelNo": "",
		  "goodsPermission": "all",
		  "goodsPermissionGroup": "",
		  "goodsPermissionPriceStringFl": "n",
		  "goodsPermissionPriceString": "",
		  "onlyAdultFl": "n",
		  "onlyAdultImageFl": "n",
		  "taxFreeFl": "t",
		  "taxPercent": "10.0",
		  "goodsWeight": "0.00",
		  "totalStock": "0",
		  "stockFl": "n",
		  "soldOutFl": "n",
		  "fixedSales": "option",
		  "fixedOrderCnt": "option",
		  "salesUnit": "1",
		  "minOrderCnt": "1",
		  "maxOrderCnt": "0",
		  "salesStartYmd": "0000-00-00 00:00:00",
		  "salesEndYmd": "0000-00-00 00:00:00",
		  "mileageFl": "c",
		  "mileageGroup": "all",
		  "mileageGoods": "0.00",
		  "mileageGoodsUnit": "percent",
		  "mileageGroupInfo": "",
		  "mileageGroupMemberInfo": "{}",
		  "fixedGoodsDiscount": "",
		  "goodsDiscountGroup": "all",
		  "goodsDiscountGroupMemberInfo": "{}",
		  "exceptBenefit": "",
		  "exceptBenefitGroup": "",
		  "exceptBenefitGroupInfo": "",
		  "payLimitFl": "n",
		  "payLimit": "",
		  "goodsPriceString": "",
		  "optionFl": "n",
		  "optionTextFl": "n",
		  "addGoodsFl": "n",
		  "addGoods": [],
		  "deliverySno": "6047",
		  "goodsUnitPrice1": "13460.00",
		  "goodsUnitPrice2": "13325.00",
		  "goodsUnitPrice3": "13190.00",
		  "goodsUnitPrice4": "13056.00",
		  "goodsUnitPrice5": "12921.00",
		  "goodsUnitPrice6": "12787.00",
		  "goodsUnitPrice7": "12652.00",
		  "goodsUnitPrice8": "12517.00",
		  "goodsUnitPrice9": "12383.00",
		  "goodsUnitPrice10": "12248.00",
		  "optionCostPrice": "0.00",
		  "optionCode": "",
		  "optionViewFl": "y",
		  "optionSellFl": "y",
		  "stockCnt": "0",
		  "optionValue1": "",
		  "optionValue2": "",
		  "optionValue3": "",
		  "optionValue4": "",
		  "optionValue5": "",
		  "optionMemo": "",
		  "optionGoodsUnitprice1": "",
		  "optionGoodsUnitprice2": "",
		  "optionGoodsUnitprice3": "",
		  "optionGoodsUnitprice4": "",
		  "optionGoodsUnitprice5": "",
		  "optionGoodsUnitprice6": "",
		  "optionGoodsUnitprice7": "",
		  "optionGoodsUnitprice8": "",
		  "optionGoodsUnitprice9": "",
		  "optionGoodsUnitprice10": "",
		  "imageSize": "0",
		  "goodsNmStandard": "건조대 실내 건조대1단",
		  "cateAllCd": [
			{
			  "sno": "11595964",
			  "cateCd": "004",
			  "cateLinkFl": "y",
			  "goodsSort": 0,
			  "fixSort": 0
			},
			{
			  "sno": "11595965",
			  "cateCd": "004015",
			  "cateLinkFl": "y",
			  "goodsSort": 0,
			  "fixSort": 0
			},
			{
			  "sno": "11595966",
			  "cateCd": "004015003",
			  "cateLinkFl": "y",
			  "goodsSort": 0,
			  "fixSort": 0
			},
			{
			  "sno": "11595967",
			  "cateCd": "004015003001",
			  "cateLinkFl": "y",
			  "goodsSort": 0,
			  "fixSort": 0
			}
		  ],
		  "addGoodsMustFl": null,
		  "orderPossible": "y",
		  "stockOver": "n",
		  "orderPossibleMessageList": [],
		  "goodsPriceDisplayFl": "y",
		  "duplicationGoods": "n",
		  "goodsType": "goods",
		  "goodsImage": "<img src=\"https://shop-phinf.pstatic.net/20180910_43/lohas500_1536547272759o18V8_JPEG/22794581850052948_1803468939.jpg?type=m510\" width=\"40\" alt=\"건조대 실내 건조대1단\" title=\"건조대 실내 건조대1단\" class=\"middle\" class=\"imgsize-s\" />",
		  "goodsMileageExcept": "n",
		  "couponBenefitExcept": "n",
		  "memberBenefitExcept": "n",
		  "timeSaleFl": false,
		  "goodsDeliveryMethodFl": "delivery",
		  "goodsDeliveryMethodFlText": "택배",
		  "optionNm": "",
		  "goodsKey": 4,
		  "goodsMileageAddInfo": {
			"mileageFl": "c",
			"mileageGroup": "all",
			"mileageGoods": "0.00",
			"mileageGoodsUnit": "percent"
		  },
		  "price": {
			"fixedPrice": "0.00",
			"costPrice": "0.00",
			"baseGoodsPrice": "13460.00",
			"baseOptionPrice": "0.00",
			"baseOptionTextPrice": 0,
			"goodsPrice": "13460.00",
			"optionPrice": "0.00",
			"optionCostPrice": "0.00",
			"optionTextPrice": 0,
			"goodsPriceSum": 13460,
			"optionPriceSum": 0,
			"optionTextPriceSum": 0,
			"addGoodsPriceSum": 0,
			"addGoodsVat": {
			  "supply": 0,
			  "tax": 0
			},
			"goodsDcPrice": 0,
			"memberDcPrice": 0,
			"memberOverlapDcPrice": 0,
			"couponGoodsDcPrice": null,
			"goodsDeliveryPrice": 0,
			"timeSalePrice": null,
			"goodsCnt": "1",
			"goodsMemberBankDcPrice": 0,
			"goodsMemberDcPrice": 0,
			"goodsMemberOverlapDcPrice": 0,
			"goodsCouponGoodsDcPrice": 0,
			"addGoodsMemberDcPrice": 0,
			"addGoodsMemberOverlapDcPrice": 0,
			"addGoodsCouponGoodsDcPrice": 0,
			"goodsPriceSubtotal": 13460,
			"goodsVat": {
			  "supply": 12237,
			  "tax": "1223"
			},
			"goodsDeliveryAreaPrice": 0,
			"goodsDeliveryCollectPrice": 0,
			"goodsDeliveryWholeFreePrice": 0
		  },
		  "option": [],
		  "optionText": [],
		  "mileage": {
			"goodsMileage": 134,
			"memberMileage": null,
			"couponGoodsMileage": null,
			"goodsGoodsMileage": 0,
			"goodsMemberMileage": 0,
			"goodsCouponGoodsMileage": 0,
			"addGoodsGoodsMileage": 0,
			"addGoodsMemberMileage": 0,
			"addGoodsCouponGoodsMileage": 0
		  },
		  "coupon": [],
		  "memberDcInfo": "{\"addDcFl\":null,\"overlapDcFl\":null,\"memberDcPrice\":0,\"memberBankDcPrice\":0,\"memberOverlapDcPrice\":0,\"dcPercent\":null,\"overlapDcPercent\":null,\"goodsCnt\":\"1\"}",
		  "addDcFl": null,
		  "overlapDcFl": null,
		  "priceInfo": "{\"fixedPrice\":\"0.00\",\"costPrice\":\"0.00\",\"baseGoodsPrice\":\"13460.00\",\"baseOptionPrice\":\"0.00\",\"baseOptionTextPrice\":0,\"goodsPrice\":\"13460.00\",\"optionPrice\":\"0.00\",\"optionCostPrice\":\"0.00\",\"optionTextPrice\":0,\"goodsPriceSum\":13460,\"optionPriceSum\":0,\"optionTextPriceSum\":0,\"addGoodsPriceSum\":0,\"addGoodsVat\":{\"supply\":0,\"tax\":0},\"goodsDcPrice\":0,\"memberDcPrice\":0,\"memberOverlapDcPrice\":0,\"couponGoodsDcPrice\":null,\"goodsDeliveryPrice\":0,\"timeSalePrice\":null,\"goodsCnt\":\"1\",\"goodsMemberBankDcPrice\":0,\"goodsMemberDcPrice\":0,\"goodsMemberOverlapDcPrice\":0,\"goodsCouponGoodsDcPrice\":0,\"addGoodsMemberDcPrice\":0,\"addGoodsMemberOverlapDcPrice\":0,\"addGoodsCouponGoodsDcPrice\":0,\"goodsPriceSubtotal\":13460,\"goodsVat\":{\"supply\":12237,\"tax\":\"1223\"}}",
		  "mileageInfo": "{\"goodsMileage\":134,\"memberMileage\":null,\"couponGoodsMileage\":null,\"goodsGoodsMileage\":0,\"goodsMemberMileage\":0,\"goodsCouponGoodsMileage\":0,\"addGoodsGoodsMileage\":0,\"addGoodsMemberMileage\":0,\"addGoodsCouponGoodsMileage\":0,\"goodsCnt\":\"1\"}",
		  "goodsDcPricePrint": 13460,
		  "memberDcTotalPercent": "0%",
		  "memberDcPricePrint": 13460,
		  "periodDiscountEndPrint": "",
		  "goodsDeliveryFl": "y",
		  "goodsDeliveryFixFl": "fixed",
		  "goodsDeliveryMethod": "배송비 2500원",
		  "goodsDeliveryCollectFl": "pre",
		  "goodsDeliveryWholeFreeFl": "n",
		  "goodsDeliveryTaxFreeFl": "t",
		  "goodsDeliveryTaxPercent": "10.0"
		}
	  ]
	},
	"740": {
	  "5274": [
		{
		  "sno": "81110",
		  "siteKey": "6ecb051146999ad8f9e3b2ed52f0426b",
		  "mallSno": "1",
		  "directCart": "n",
		  "memNo": "0",
		  "goodsNo": "1002548620",
		  "optionSno": "11200832",
		  "goodsCnt": "1",
		  "deliveryCollectFl": "pre",
		  "deliveryMethodFl": "delivery",
		  "memberCouponNo": "",
		  "tmpOrderNo": "",
		  "useBundleGoods": "1",
		  "linkMainTheme": "",
		  "regDt": "2019-01-17 15:22:36",
		  "goodsNm": "sansui 원목 천연가습기 겸 아로마디퓨저",
		  "goodsDisplayFl": "y",
		  "goodsDisplayMobileFl": "y",
		  "goodsSellFl": "y",
		  "goodsSellMobileFl": "y",
		  "scmNo": "740",
		  "commission": "8.00",
		  "goodsCd": "",
		  "cateCd": "003002001004",
		  "goodsOpenDt": "0000-00-00 00:00:00",
		  "goodsState": "n",
		  "brandCd": "",
		  "makerNm": "",
		  "originNm": "",
		  "hscode": "",
		  "goodsModelNo": "",
		  "goodsPermission": "all",
		  "goodsPermissionGroup": "",
		  "goodsPermissionPriceStringFl": "n",
		  "goodsPermissionPriceString": "",
		  "onlyAdultFl": "n",
		  "onlyAdultImageFl": "n",
		  "taxFreeFl": "t",
		  "taxPercent": "10.0",
		  "goodsWeight": "0.00",
		  "totalStock": "0",
		  "stockFl": "n",
		  "soldOutFl": "n",
		  "fixedSales": "option",
		  "fixedOrderCnt": "option",
		  "salesUnit": "1",
		  "minOrderCnt": "1",
		  "maxOrderCnt": "0",
		  "salesStartYmd": "0000-00-00 00:00:00",
		  "salesEndYmd": "0000-00-00 00:00:00",
		  "mileageFl": "c",
		  "mileageGroup": "all",
		  "mileageGoods": "0.00",
		  "mileageGoodsUnit": "percent",
		  "mileageGroupInfo": "",
		  "mileageGroupMemberInfo": "{}",
		  "fixedGoodsDiscount": "",
		  "goodsDiscountGroup": "all",
		  "goodsDiscountGroupMemberInfo": "{}",
		  "exceptBenefit": "",
		  "exceptBenefitGroup": "",
		  "exceptBenefitGroupInfo": "",
		  "payLimitFl": "n",
		  "payLimit": "",
		  "goodsPriceString": "",
		  "optionFl": "y",
		  "optionTextFl": "n",
		  "addGoodsFl": "n",
		  "addGoods": [],
		  "deliverySno": "5274",
		  "goodsUnitPrice1": "79800.00",
		  "goodsUnitPrice2": "79002.00",
		  "goodsUnitPrice3": "78204.00",
		  "goodsUnitPrice4": "77406.00",
		  "goodsUnitPrice5": "76608.00",
		  "goodsUnitPrice6": "75810.00",
		  "goodsUnitPrice7": "75012.00",
		  "goodsUnitPrice8": "74214.00",
		  "goodsUnitPrice9": "73416.00",
		  "goodsUnitPrice10": "72618.00",
		  "optionCostPrice": "0.00",
		  "optionCode": "",
		  "optionViewFl": "y",
		  "optionSellFl": "y",
		  "stockCnt": "0",
		  "optionMemo": "",
		  "optionGoodsUnitprice1": "103800",
		  "optionGoodsUnitprice2": "102762",
		  "optionGoodsUnitprice3": "101724",
		  "optionGoodsUnitprice4": "100686",
		  "optionGoodsUnitprice5": "99648",
		  "optionGoodsUnitprice6": "98610",
		  "optionGoodsUnitprice7": "97572",
		  "optionGoodsUnitprice8": "96534",
		  "optionGoodsUnitprice9": "95496",
		  "optionGoodsUnitprice10": "94458",
		  "imageSize": "0",
		  "goodsNmStandard": "sansui 원목 천연가습기 겸 아로마디퓨저",
		  "cateAllCd": [
			{
			  "sno": "12547783",
			  "cateCd": "003",
			  "cateLinkFl": "y",
			  "goodsSort": 0,
			  "fixSort": 0
			},
			{
			  "sno": "12547784",
			  "cateCd": "003002",
			  "cateLinkFl": "y",
			  "goodsSort": 0,
			  "fixSort": 0
			},
			{
			  "sno": "12547785",
			  "cateCd": "003002001",
			  "cateLinkFl": "y",
			  "goodsSort": 0,
			  "fixSort": 0
			},
			{
			  "sno": "12547786",
			  "cateCd": "003002001004",
			  "cateLinkFl": "y",
			  "goodsSort": 0,
			  "fixSort": 0
			}
		  ],
		  "addGoodsMustFl": null,
		  "orderPossible": "y",
		  "stockOver": "n",
		  "orderPossibleMessageList": [],
		  "goodsPriceDisplayFl": "y",
		  "duplicationGoods": "n",
		  "goodsType": "goods",
		  "goodsImage": "<img src=\"https://shop-phinf.pstatic.net/20181123_204/comeva_154291308240174cXe_JPEG/66219383020952631_1634903573.jpg?type=m510\" width=\"40\" alt=\"sansui 원목 천연가습기 겸 아로마디퓨저\" title=\"sansui 원목 천연가습기 겸 아로마디퓨저\" class=\"middle\" class=\"imgsize-s\" />",
		  "goodsMileageExcept": "n",
		  "couponBenefitExcept": "n",
		  "memberBenefitExcept": "n",
		  "timeSaleFl": false,
		  "goodsDeliveryMethodFl": "delivery",
		  "goodsDeliveryMethodFlText": "택배",
		  "optionNm": "옵션 02. 2.목제하판 포함",
		  "goodsKey": 1,
		  "goodsMileageAddInfo": {
			"mileageFl": "c",
			"mileageGroup": "all",
			"mileageGoods": "0.00",
			"mileageGoodsUnit": "percent"
		  },
		  "price": {
			"fixedPrice": "0.00",
			"costPrice": "0.00",
			"baseGoodsPrice": "103800",
			"baseOptionPrice": "0.00",
			"baseOptionTextPrice": 0,
			"goodsPrice": "103800",
			"optionPrice": "0.00",
			"optionCostPrice": "0.00",
			"optionTextPrice": 0,
			"goodsPriceSum": 103800,
			"optionPriceSum": 0,
			"optionTextPriceSum": 0,
			"addGoodsPriceSum": 0,
			"addGoodsVat": {
			  "supply": 0,
			  "tax": 0
			},
			"goodsDcPrice": 0,
			"memberDcPrice": 0,
			"memberOverlapDcPrice": 0,
			"couponGoodsDcPrice": null,
			"goodsDeliveryPrice": 0,
			"timeSalePrice": null,
			"goodsCnt": "1",
			"goodsMemberBankDcPrice": 0,
			"goodsMemberDcPrice": 0,
			"goodsMemberOverlapDcPrice": 0,
			"goodsCouponGoodsDcPrice": 0,
			"addGoodsMemberDcPrice": 0,
			"addGoodsMemberOverlapDcPrice": 0,
			"addGoodsCouponGoodsDcPrice": 0,
			"goodsPriceSubtotal": 103800,
			"goodsVat": {
			  "supply": 94364,
			  "tax": "9436"
			},
			"goodsDeliveryAreaPrice": 0,
			"goodsDeliveryCollectPrice": 0,
			"goodsDeliveryWholeFreePrice": 0
		  },
		  "option": [
			{
			  "optionName": "옵션선택",
			  "optionValue": "옵션 02. 2.목제하판 포함",
			  "optionPrice": "0.00",
			  "optionCode": ""
			}
		  ],
		  "optionText": [],
		  "mileage": {
			"goodsMileage": 1038,
			"memberMileage": null,
			"couponGoodsMileage": null,
			"goodsGoodsMileage": 0,
			"goodsMemberMileage": 0,
			"goodsCouponGoodsMileage": 0,
			"addGoodsGoodsMileage": 0,
			"addGoodsMemberMileage": 0,
			"addGoodsCouponGoodsMileage": 0
		  },
		  "coupon": [],
		  "memberDcInfo": "{\"addDcFl\":null,\"overlapDcFl\":null,\"memberDcPrice\":0,\"memberBankDcPrice\":0,\"memberOverlapDcPrice\":0,\"dcPercent\":null,\"overlapDcPercent\":null,\"goodsCnt\":\"1\"}",
		  "addDcFl": null,
		  "overlapDcFl": null,
		  "priceInfo": "{\"fixedPrice\":\"0.00\",\"costPrice\":\"0.00\",\"baseGoodsPrice\":\"103800\",\"baseOptionPrice\":\"0.00\",\"baseOptionTextPrice\":0,\"goodsPrice\":\"103800\",\"optionPrice\":\"0.00\",\"optionCostPrice\":\"0.00\",\"optionTextPrice\":0,\"goodsPriceSum\":103800,\"optionPriceSum\":0,\"optionTextPriceSum\":0,\"addGoodsPriceSum\":0,\"addGoodsVat\":{\"supply\":0,\"tax\":0},\"goodsDcPrice\":0,\"memberDcPrice\":0,\"memberOverlapDcPrice\":0,\"couponGoodsDcPrice\":null,\"goodsDeliveryPrice\":0,\"timeSalePrice\":null,\"goodsCnt\":\"1\",\"goodsMemberBankDcPrice\":0,\"goodsMemberDcPrice\":0,\"goodsMemberOverlapDcPrice\":0,\"goodsCouponGoodsDcPrice\":0,\"addGoodsMemberDcPrice\":0,\"addGoodsMemberOverlapDcPrice\":0,\"addGoodsCouponGoodsDcPrice\":0,\"goodsPriceSubtotal\":103800,\"goodsVat\":{\"supply\":94364,\"tax\":\"9436\"}}",
		  "mileageInfo": "{\"goodsMileage\":1038,\"memberMileage\":null,\"couponGoodsMileage\":null,\"goodsGoodsMileage\":0,\"goodsMemberMileage\":0,\"goodsCouponGoodsMileage\":0,\"addGoodsGoodsMileage\":0,\"addGoodsMemberMileage\":0,\"addGoodsCouponGoodsMileage\":0,\"goodsCnt\":\"1\"}",
		  "goodsDcPricePrint": 103800,
		  "memberDcTotalPercent": "0%",
		  "memberDcPricePrint": 103800,
		  "periodDiscountEndPrint": "",
		  "goodsDeliveryFl": "y",
		  "goodsDeliveryFixFl": "free",
		  "goodsDeliveryMethod": "기본 - 배송비무료",
		  "goodsDeliveryCollectFl": "pre",
		  "goodsDeliveryWholeFreeFl": true,
		  "goodsDeliveryTaxFreeFl": "t",
		  "goodsDeliveryTaxPercent": "10.0"
		}
	  ]
	},
	"755": {
	  "5961": [
		{
		  "sno": "81172",
		  "siteKey": "6ecb051146999ad8f9e3b2ed52f0426b",
		  "mallSno": "1",
		  "directCart": "n",
		  "memNo": "0",
		  "goodsNo": "1002564700",
		  "optionSno": "11240143",
		  "goodsCnt": "1",
		  "deliveryCollectFl": "pre",
		  "deliveryMethodFl": "delivery",
		  "memberCouponNo": "",
		  "tmpOrderNo": "",
		  "useBundleGoods": "1",
		  "linkMainTheme": "",
		  "regDt": "2019-01-17 16:24:04",
		  "goodsNm": "마슘환 2개 고급말뼈환 말뼈가루환 천연칼슘식품",
		  "goodsDisplayFl": "y",
		  "goodsDisplayMobileFl": "y",
		  "goodsSellFl": "y",
		  "goodsSellMobileFl": "y",
		  "scmNo": "755",
		  "commission": "12.00",
		  "goodsCd": "",
		  "cateCd": "006002008015",
		  "goodsOpenDt": "0000-00-00 00:00:00",
		  "goodsState": "n",
		  "brandCd": "",
		  "makerNm": "",
		  "originNm": "",
		  "hscode": "",
		  "goodsModelNo": "",
		  "goodsPermission": "all",
		  "goodsPermissionGroup": "",
		  "goodsPermissionPriceStringFl": "n",
		  "goodsPermissionPriceString": "",
		  "onlyAdultFl": "n",
		  "onlyAdultImageFl": "n",
		  "taxFreeFl": "t",
		  "taxPercent": "10.0",
		  "goodsWeight": "0.00",
		  "totalStock": "0",
		  "stockFl": "n",
		  "soldOutFl": "n",
		  "fixedSales": "option",
		  "fixedOrderCnt": "option",
		  "salesUnit": "1",
		  "minOrderCnt": "1",
		  "maxOrderCnt": "0",
		  "salesStartYmd": "0000-00-00 00:00:00",
		  "salesEndYmd": "0000-00-00 00:00:00",
		  "mileageFl": "c",
		  "mileageGroup": "all",
		  "mileageGoods": "0.00",
		  "mileageGoodsUnit": "percent",
		  "mileageGroupInfo": "",
		  "mileageGroupMemberInfo": "{}",
		  "fixedGoodsDiscount": "",
		  "goodsDiscountGroup": "all",
		  "goodsDiscountGroupMemberInfo": "{}",
		  "exceptBenefit": "",
		  "exceptBenefitGroup": "",
		  "exceptBenefitGroupInfo": "",
		  "payLimitFl": "n",
		  "payLimit": "",
		  "goodsPriceString": "",
		  "optionFl": "n",
		  "optionTextFl": "n",
		  "addGoodsFl": "n",
		  "addGoods": [],
		  "deliverySno": "5961",
		  "goodsUnitPrice1": "110000.00",
		  "goodsUnitPrice2": "108900.00",
		  "goodsUnitPrice3": "107800.00",
		  "goodsUnitPrice4": "106700.00",
		  "goodsUnitPrice5": "105600.00",
		  "goodsUnitPrice6": "104500.00",
		  "goodsUnitPrice7": "103400.00",
		  "goodsUnitPrice8": "102300.00",
		  "goodsUnitPrice9": "101200.00",
		  "goodsUnitPrice10": "100100.00",
		  "optionCostPrice": "0.00",
		  "optionCode": "",
		  "optionViewFl": "y",
		  "optionSellFl": "y",
		  "stockCnt": "0",
		  "optionValue1": "",
		  "optionValue2": "",
		  "optionValue3": "",
		  "optionValue4": "",
		  "optionValue5": "",
		  "optionMemo": "",
		  "optionGoodsUnitprice1": "",
		  "optionGoodsUnitprice2": "",
		  "optionGoodsUnitprice3": "",
		  "optionGoodsUnitprice4": "",
		  "optionGoodsUnitprice5": "",
		  "optionGoodsUnitprice6": "",
		  "optionGoodsUnitprice7": "",
		  "optionGoodsUnitprice8": "",
		  "optionGoodsUnitprice9": "",
		  "optionGoodsUnitprice10": "",
		  "imageSize": "0",
		  "goodsNmStandard": "마슘환 2개 고급말뼈환 말뼈가루환 천연칼슘식품",
		  "cateAllCd": [
			{
			  "sno": "12608619",
			  "cateCd": "006",
			  "cateLinkFl": "y",
			  "goodsSort": 0,
			  "fixSort": 0
			},
			{
			  "sno": "12608620",
			  "cateCd": "006002",
			  "cateLinkFl": "y",
			  "goodsSort": 0,
			  "fixSort": 0
			},
			{
			  "sno": "12608621",
			  "cateCd": "006002008",
			  "cateLinkFl": "y",
			  "goodsSort": 0,
			  "fixSort": 0
			},
			{
			  "sno": "12608622",
			  "cateCd": "006002008015",
			  "cateLinkFl": "y",
			  "goodsSort": 0,
			  "fixSort": 0
			}
		  ],
		  "addGoodsMustFl": null,
		  "orderPossible": "y",
		  "stockOver": "n",
		  "orderPossibleMessageList": [],
		  "goodsPriceDisplayFl": "y",
		  "duplicationGoods": "n",
		  "goodsType": "goods",
		  "goodsImage": "<img src=\"https://shop-phinf.pstatic.net/20190105_62/ncp_1nmytc_01_1546659027586gCunK_JPEG/v1.jpg?type=m510\" width=\"40\" alt=\"마슘환 2개 고급말뼈환 말뼈가루환 천연칼슘식품\" title=\"마슘환 2개 고급말뼈환 말뼈가루환 천연칼슘식품\" class=\"middle\" class=\"imgsize-s\" />",
		  "goodsMileageExcept": "n",
		  "couponBenefitExcept": "n",
		  "memberBenefitExcept": "n",
		  "timeSaleFl": false,
		  "goodsDeliveryMethodFl": "delivery",
		  "goodsDeliveryMethodFlText": "택배",
		  "optionNm": "",
		  "goodsKey": 0,
		  "goodsMileageAddInfo": {
			"mileageFl": "c",
			"mileageGroup": "all",
			"mileageGoods": "0.00",
			"mileageGoodsUnit": "percent"
		  },
		  "price": {
			"fixedPrice": "0.00",
			"costPrice": "0.00",
			"baseGoodsPrice": "110000.00",
			"baseOptionPrice": "0.00",
			"baseOptionTextPrice": 0,
			"goodsPrice": "110000.00",
			"optionPrice": "0.00",
			"optionCostPrice": "0.00",
			"optionTextPrice": 0,
			"goodsPriceSum": 110000,
			"optionPriceSum": 0,
			"optionTextPriceSum": 0,
			"addGoodsPriceSum": 0,
			"addGoodsVat": {
			  "supply": 0,
			  "tax": 0
			},
			"goodsDcPrice": 0,
			"memberDcPrice": 0,
			"memberOverlapDcPrice": 0,
			"couponGoodsDcPrice": null,
			"goodsDeliveryPrice": 0,
			"timeSalePrice": null,
			"goodsCnt": "1",
			"goodsMemberBankDcPrice": 0,
			"goodsMemberDcPrice": 0,
			"goodsMemberOverlapDcPrice": 0,
			"goodsCouponGoodsDcPrice": 0,
			"addGoodsMemberDcPrice": 0,
			"addGoodsMemberOverlapDcPrice": 0,
			"addGoodsCouponGoodsDcPrice": 0,
			"goodsPriceSubtotal": 110000,
			"goodsVat": {
			  "supply": 100000,
			  "tax": "10000"
			},
			"goodsDeliveryAreaPrice": 0,
			"goodsDeliveryCollectPrice": 0,
			"goodsDeliveryWholeFreePrice": 0
		  },
		  "option": [],
		  "optionText": [],
		  "mileage": {
			"goodsMileage": 1100,
			"memberMileage": null,
			"couponGoodsMileage": null,
			"goodsGoodsMileage": 0,
			"goodsMemberMileage": 0,
			"goodsCouponGoodsMileage": 0,
			"addGoodsGoodsMileage": 0,
			"addGoodsMemberMileage": 0,
			"addGoodsCouponGoodsMileage": 0
		  },
		  "coupon": [],
		  "memberDcInfo": "{\"addDcFl\":null,\"overlapDcFl\":null,\"memberDcPrice\":0,\"memberBankDcPrice\":0,\"memberOverlapDcPrice\":0,\"dcPercent\":null,\"overlapDcPercent\":null,\"goodsCnt\":\"1\"}",
		  "addDcFl": null,
		  "overlapDcFl": null,
		  "priceInfo": "{\"fixedPrice\":\"0.00\",\"costPrice\":\"0.00\",\"baseGoodsPrice\":\"110000.00\",\"baseOptionPrice\":\"0.00\",\"baseOptionTextPrice\":0,\"goodsPrice\":\"110000.00\",\"optionPrice\":\"0.00\",\"optionCostPrice\":\"0.00\",\"optionTextPrice\":0,\"goodsPriceSum\":110000,\"optionPriceSum\":0,\"optionTextPriceSum\":0,\"addGoodsPriceSum\":0,\"addGoodsVat\":{\"supply\":0,\"tax\":0},\"goodsDcPrice\":0,\"memberDcPrice\":0,\"memberOverlapDcPrice\":0,\"couponGoodsDcPrice\":null,\"goodsDeliveryPrice\":0,\"timeSalePrice\":null,\"goodsCnt\":\"1\",\"goodsMemberBankDcPrice\":0,\"goodsMemberDcPrice\":0,\"goodsMemberOverlapDcPrice\":0,\"goodsCouponGoodsDcPrice\":0,\"addGoodsMemberDcPrice\":0,\"addGoodsMemberOverlapDcPrice\":0,\"addGoodsCouponGoodsDcPrice\":0,\"goodsPriceSubtotal\":110000,\"goodsVat\":{\"supply\":100000,\"tax\":\"10000\"}}",
		  "mileageInfo": "{\"goodsMileage\":1100,\"memberMileage\":null,\"couponGoodsMileage\":null,\"goodsGoodsMileage\":0,\"goodsMemberMileage\":0,\"goodsCouponGoodsMileage\":0,\"addGoodsGoodsMileage\":0,\"addGoodsMemberMileage\":0,\"addGoodsCouponGoodsMileage\":0,\"goodsCnt\":\"1\"}",
		  "goodsDcPricePrint": 110000,
		  "memberDcTotalPercent": "0%",
		  "memberDcPricePrint": 110000,
		  "periodDiscountEndPrint": "",
		  "goodsDeliveryFl": "y",
		  "goodsDeliveryFixFl": "free",
		  "goodsDeliveryMethod": "기본 - 배송비무료",
		  "goodsDeliveryCollectFl": "pre",
		  "goodsDeliveryWholeFreeFl": true,
		  "goodsDeliveryTaxFreeFl": "t",
		  "goodsDeliveryTaxPercent": "10.0"
		}
	  ]
	}
}

let initialTempDelivery =(window.setDeliveryInfo)?window.setDeliveryInfo: {
	"2906": {
	  "deliveryByStandard": 0,
	  "deliveryByCalculate": "n",
	  "fixFl": "free",
	  "goodsDeliveryWholeFreeFl": "y",
	  "goodsDeliveryCollectFl": "pre",
	  "scmNo": 414,
	  "goodsLineCnt": 1,
	  "addGoodsLineCnt": 0,
	  "goodsDeliveryMethodFl": "delivery",
	  "goodsDeliveryMethodFlText": "택배",
	  "goodsDeliveryMethod": "기본 - 배송비무료",
	  "goodsDeliveryPrice": 0
	},
	"4800": {
	  "deliveryByStandard": 0,
	  "deliveryByCalculate": "n",
	  "fixFl": "fixed",
	  "goodsDeliveryWholeFreeFl": null,
	  "goodsDeliveryCollectFl": "pre",
	  "scmNo": 672,
	  "goodsLineCnt": 1,
	  "addGoodsLineCnt": 0,
	  "goodsDeliveryMethodFl": "delivery",
	  "goodsDeliveryMethodFlText": "택배",
	  "goodsDeliveryMethod": "기본 - 고정배송비",
	  "goodsDeliveryPrice": "2500.00"
	},
	"5274": {
	  "deliveryByStandard": 0,
	  "deliveryByCalculate": "n",
	  "fixFl": "free",
	  "goodsDeliveryWholeFreeFl": "y",
	  "goodsDeliveryCollectFl": "pre",
	  "scmNo": 740,
	  "goodsLineCnt": 1,
	  "addGoodsLineCnt": 0,
	  "goodsDeliveryMethodFl": "delivery",
	  "goodsDeliveryMethodFlText": "택배",
	  "goodsDeliveryMethod": "기본 - 배송비무료",
	  "goodsDeliveryPrice": 0
	},
	"5961": {
	  "deliveryByStandard": 0,
	  "deliveryByCalculate": "n",
	  "fixFl": "free",
	  "goodsDeliveryWholeFreeFl": "y",
	  "goodsDeliveryCollectFl": "pre",
	  "scmNo": 755,
	  "goodsLineCnt": 1,
	  "addGoodsLineCnt": 0,
	  "goodsDeliveryMethodFl": "delivery",
	  "goodsDeliveryMethodFlText": "택배",
	  "goodsDeliveryMethod": "기본 - 배송비무료",
	  "goodsDeliveryPrice": 0
	},
	"6047": {
	  "deliveryByStandard": 0,
	  "deliveryByCalculate": "n",
	  "fixFl": "fixed",
	  "goodsDeliveryWholeFreeFl": null,
	  "goodsDeliveryCollectFl": "pre",
	  "scmNo": 737,
	  "goodsLineCnt": 1,
	  "addGoodsLineCnt": 0,
	  "goodsDeliveryMethodFl": "delivery",
	  "goodsDeliveryMethodFlText": "택배",
	  "goodsDeliveryMethod": "배송비 2500원",
	  "goodsDeliveryPrice": "2500.00"
	}
};
let initialTempScmInfo = (window.cartScmInfo)? window.cartScmInfo:{
	"414": {
	  "scmNo": "414",
	  "companyNm": "자동차용품 티커벨",
	  "scmType": "y",
	  "scmKind": "p"
	},
	"672": {
	  "scmNo": "672",
	  "companyNm": "(주)프린트플랜",
	  "scmType": "y",
	  "scmKind": "p"
	},
	"737": {
	  "scmNo": "737",
	  "companyNm": "주식회사로하스",
	  "scmType": "y",
	  "scmKind": "p"
	},
	"740": {
	  "scmNo": "740",
	  "companyNm": "페퍼클럽",
	  "scmType": "y",
	  "scmKind": "p"
	},
	"755": {
	  "scmNo": "755",
	  "companyNm": "장보고",
	  "scmType": "y",
	  "scmKind": "p"
	}
}
export const initialCartDataList = [];
Object.keys(initialTempCart).map((scmNo)=>{
	let matchedScmKeys = Object.keys(initialTempScmInfo).filter((tempScmKey)=> scmNo==tempScmKey);
	let scmInfo = (matchedScmKeys)?initialTempScmInfo[matchedScmKeys[0]]:{};
	Object.keys(initialTempCart[scmNo]).map((deliveryNo)=>{
		let matchedDeliveryKeys = Object.keys(initialTempDelivery).filter((tempDeliveryKey)=>tempDeliveryKey==deliveryNo);
		let deliveryInfo = (matchedDeliveryKeys)?initialTempDelivery[matchedDeliveryKeys[0]]:{};
		initialTempCart[scmNo][matchedDeliveryKeys].map((cartData)=>{
			cartData['scmInfo'] = scmInfo;
			cartData['deliveryInfo'] = deliveryInfo;
			let regex = /<img.*?src="(.*?)"/;
			let src = regex.exec(cartData.goodsImage)[1];
			cartData['goodsImage'] = src;
			cartData.goodsCnt = parseInt(cartData.goodsCnt);
			if(cartData.optionFl=='y'){
				cartData['price']['baseGoodsPrice'] = parseInt(cartData.optionGoodsUnitprice1);
			}
			else{
				cartData['price']['baseGoodsPrice'] = parseInt(cartData.goodsUnitPrice1);

			}
			initialCartDataList.push(cartData);
		})
	})
})
const  CartReducer = (state = initialCartDataList, action) => {
	switch (action.type) {
		default: return state
		case cartAction.CHANGE_COUNT:
			return [
			...state.map(cartData=>{
				if(cartData.sno==action.sno){
					if(cartData.goodsCnt + action.changeCount <= 0 ){
						return {
							...cartData,
							cartUpdated: 
							initialCartDataList.filter(originCartObj=>originCartObj.sno==action.sno)[0].goodsCnt
							!= cartData.goodsCnt + action.changeCount 
						};
					}
					else{
						 let newGoodsCnt =cartData.goodsCnt + action.changeCount;
						 let newGoodsPrice;
						 let goodsCntString = (newGoodsCnt>10)?"10":newGoodsCnt.toString();

						 if(cartData.optionFl=='n'){
								let goodsFindKey = "goodsUnitPrice" + goodsCntString;
						  	newGoodsPrice = (cartData[goodsFindKey]&&(parseInt(cartData[goodsFindKey])>0))?cartData[goodsFindKey]:cartData["goodsUnitPrice1"];
						 }
						 else{
								let goodsFindKey = "optionGoodsUnitprice" + goodsCntString;
								newGoodsPrice = (cartData[goodsFindKey]&&cartData[goodsFindKey].length>0)?cartData[goodsFindKey]:cartData["optionGoodsUnitprice1"];
						 }
						 newGoodsPrice = parseInt(newGoodsPrice);
						 let newGoodsSum = newGoodsCnt * newGoodsPrice; 
						 return {
							 ...cartData,goodsCnt:newGoodsCnt,
							 cartUpdated:initialCartDataList.filter(originCartObj=>originCartObj.sno==action.sno)[0].goodsCnt
							 != cartData.goodsCnt + action.changeCount,
							 price:{
								 ...cartData.price,
								 goodsPriceSum:newGoodsSum,
								 goodsPrice:newGoodsPrice.toString()
	 
								}}
					}
				}
				else{
					return cartData;
				}

			})
		]
		case cartAction.DELETE_CART:
			return [
				...state.filter(cartData=>cartData.sno!=action.sno)
			]

	}
}
	

export default CartReducer;